version: '3'
services:
  local-connect:
    image: 'magrelo/local-connect:latest'
    container_name: local-connect
    restart: on-failure
    environment:
      - MONGODB_URL_INT=${MONGODB_URL_INT}

      - JWT_SECRET=${JWT_KEY}

      - SENDGRID_API_KEY=${SENDGRID_KEY}
      - SENDGRID_FROM_ADDRESS=info@localconnect.app

  # loadbalancer
  nginx:
    container_name: nginx
    build:
      context: ./nginx/prod
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/ssl:/etc/ssl
      - /etc/letsencrypt:/etc/letsencrypt
      - /data/letsencrypt:/data/letsencrypt
