version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    command: mongod --logpath=/dev/null # --quiet

  ie-marketing:
    image: 'magrelo/ie-marketing:latest'
    container_name: ie-marketing
    restart: on-failure
    # environment:
    #   - MONGODB_URL_INT=mongodb://mongodb:27017/ie-app
    #   - PLAID_CLIENT_APP_NAME="Incentive Exchange"
    #   - PLAID_CLIENT_ID=5d0cdd955a4c3e0012b14f6e
    #   - PLAID_SECRET=ac69552f4c2f146f9a8ee31686e7ec
    #   - PLAID_PUBLIC_KEY=2b3f9221802f14178deef36cd7f168
    #   - PLAID_ENV=sandbox
    #   - STRIPE_KEY=""
    #   - STRIPE_TEST_MODE="true"
    #   - STRIPE_TEST_KEY="sk_test_yXADfBHmXOanF981juFqbgyW00dsT1QRFj"
    #   - TWITTER_CONSUMER_KEY=3xMYwM4puMqa9bYWt120vpFQM
    #   - TWITTER_CONSUMER_SECRET=hg3CRbyCBPmZNgfGMJob5kZeUjvF9R5YjXEcqsyDSf9Eqn96uL
    #   - TWITTER_CALLBACK=https://incentive.exchange/twitter-callback
    #   - JWT_SECRET=pasta
    #   - SENDGRID_API_KEY=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
    #   - SENDGRID_FROM_ADDRESS=dealflow@incentive.exchange
    # depends_on:
    #   - mongodb

  ie-app:
    image: 'magrelo/ie-app:latest'
    container_name: ie-app
    restart: on-failure
    environment:
      - MONGODB_URL_INT=mongodb://mongodb:27017/ie-app
      - PLAID_CLIENT_APP_NAME="Incentive Exchange"
      - PLAID_CLIENT_ID=5d0cdd955a4c3e0012b14f6e
      - PLAID_SECRET=ac69552f4c2f146f9a8ee31686e7ec
      - PLAID_PUBLIC_KEY=2b3f9221802f14178deef36cd7f168
      - PLAID_ENV=sandbox
      - STRIPE_KEY=""
      - STRIPE_TEST_MODE="true"
      - STRIPE_TEST_KEY="sk_test_yXADfBHmXOanF981juFqbgyW00dsT1QRFj"
      - TWITTER_CONSUMER_KEY=3xMYwM4puMqa9bYWt120vpFQM
      - TWITTER_CONSUMER_SECRET=hg3CRbyCBPmZNgfGMJob5kZeUjvF9R5YjXEcqsyDSf9Eqn96uL
      - TWITTER_CALLBACK=https://incentive.exchange/twitter-callback
      - JWT_SECRET=pasta
      - SENDGRID_API_KEY=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
      - SENDGRID_FROM_ADDRESS=dealflow@incentive.exchange
    depends_on:
      - mongodb

  elasticsearch:
    container_name: elasticsearch
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    # ports:
    #   - '9200:9200'
    #   - '9300:9300'
    environment:
      ES_JAVA_OPTS: '-Xmx1g -Xms1g'
      ELASTIC_PASSWORD: changeme

  kibana:
    container_name: kibana
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    # ports:
    #  - '5601:5601'
    depends_on:
      - elasticsearch

  logstash:
    container_name: logstash
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    depends_on:
      - elasticsearch

  # loadbalancer
  nginx:
    container_name: nginx
    build:
      context: ./nginx/prod
    ports:
      - '80:80'
      - '443:443'
      - '5601:5601'
      - '9200:9200'
    volumes:
      - /etc/ssl:/etc/ssl
      - /etc/letsencrypt:/etc/letsencrypt
      - /data/letsencrypt:/data/letsencrypt
    depends_on:
      - logstash
