version: '3'
services:
  homepage:
    image: 'magrelo/servesa-home:latest'
    container_name: homepage
    restart: on-failure

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      ES_JAVA_OPTS: '-Xmx1g -Xms1g'
      ELASTIC_PASSWORD: changeme

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    depends_on:
      - elasticsearch

  # loadbalancer
  nginx:
    container_name: nginx
    build:
      context: ./nginx/prod
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/ssl:/etc/ssl
      - /etc/letsencrypt:/etc/letsencrypt
      - /data/letsencrypt:/data/letsencrypt
    depends_on:
      - logstash
